/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.store": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "todo": [],
    "password-reminder.dismiss": [],
    "user-management.index": [],
    "user-management.create": [],
    "user-management.store": [],
    "user-management.disabled": [],
    "user-management.drafts": [],
    "user-management.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.disable": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.enable": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.approve": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-management.disapprove": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "task-management.index": [],
    "task-management.presets.index": [],
    "task-management.presets.create": [],
    "task-management.presets.store": [],
    "task-management.presets.show": [
        {
            "name": "preset",
            "required": true
        }
    ],
    "task-management.presets.edit": [
        {
            "name": "preset",
            "required": true
        }
    ],
    "task-management.presets.update": [
        {
            "name": "preset",
            "required": true,
            "binding": "id"
        }
    ],
    "task-management.presets.destroy": [
        {
            "name": "preset",
            "required": true,
            "binding": "id"
        }
    ],
    "task-management.users.task-presets.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "task-management.users.task-preset.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "task-management.users.task-presets.bulk-update": [],
    "reports": [],
    "user-dashboard": [],
    "login-history": [],
    "login-history.show": [
        {
            "name": "loginHistory",
            "required": true,
            "binding": "id"
        }
    ],
    "login-history.export": [],
    "active-sessions": [],
    "active-sessions.destroy": [
        {
            "name": "activeSession",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.detail": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.show": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.store": [],
    "reports.update": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.destroy": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "password.update": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
